/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalguipinakalastna.gydni;

import java.awt.Color;

/**
 *
 * @author TABANG
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    Color DefaultColor,ClickedColor;
    public DashBoard() {
        initComponents();
        
        DefaultColor = new Color(172,125,136);
        ClickedColor = new Color(253, 240, 209);
        
        Q1.setBackground(DefaultColor);
        Q2.setBackground(DefaultColor);
        Q3.setBackground(DefaultColor);
        Q4.setBackground(DefaultColor);
        Q5.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        MenuNames = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Q1 = new javax.swing.JPanel();
        T1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JPanel();
        T2 = new javax.swing.JLabel();
        Q3 = new javax.swing.JPanel();
        T3 = new javax.swing.JLabel();
        Q4 = new javax.swing.JPanel();
        T4 = new javax.swing.JLabel();
        Q5 = new javax.swing.JPanel();
        T5 = new javax.swing.JLabel();
        jDesktopPanes = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(133, 88, 111));

        jPanel2.setBackground(new java.awt.Color(253, 240, 209));

        jButton2.setBackground(new java.awt.Color(253, 240, 209));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\TABANG\\Documents\\NetBeansProjects\\FinalGuiPinakalastna-gydni\\src\\Logos\\icons8_close_window_48px.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 56, 67));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Job Application Trucker");

        jPanel5.setBackground(new java.awt.Color(253, 240, 209));

        MenuNames.setFont(new java.awt.Font("Sylfaen", 1, 10)); // NOI18N
        MenuNames.setForeground(new java.awt.Color(100, 56, 67));
        MenuNames.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuNames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_menu_26px.png"))); // NOI18N
        MenuNames.setText("MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuNames)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MenuNames))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(172, 125, 136));

        jPanel4.setBackground(new java.awt.Color(172, 125, 136));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        Q1.setBackground(new java.awt.Color(172, 125, 136));
        Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q1MousePressed(evt);
            }
        });

        T1.setForeground(new java.awt.Color(100, 56, 67));
        T1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_job_seeker_24px_1.png"))); // NOI18N
        T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                T1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Q1Layout = new javax.swing.GroupLayout(Q1);
        Q1.setLayout(Q1Layout);
        Q1Layout.setHorizontalGroup(
            Q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(T1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Q1Layout.setVerticalGroup(
            Q1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Q2.setBackground(new java.awt.Color(172, 125, 136));
        Q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q2MousePressed(evt);
            }
        });

        T2.setForeground(new java.awt.Color(100, 56, 67));
        T2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_view_24px.png"))); // NOI18N

        javax.swing.GroupLayout Q2Layout = new javax.swing.GroupLayout(Q2);
        Q2.setLayout(Q2Layout);
        Q2Layout.setHorizontalGroup(
            Q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(T2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Q2Layout.setVerticalGroup(
            Q2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Q2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(T2)
                .addContainerGap())
        );

        Q3.setBackground(new java.awt.Color(172, 125, 136));
        Q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q3MousePressed(evt);
            }
        });

        T3.setForeground(new java.awt.Color(100, 56, 67));
        T3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_details_32px.png"))); // NOI18N

        javax.swing.GroupLayout Q3Layout = new javax.swing.GroupLayout(Q3);
        Q3.setLayout(Q3Layout);
        Q3Layout.setHorizontalGroup(
            Q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(T3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Q3Layout.setVerticalGroup(
            Q3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q3Layout.createSequentialGroup()
                .addComponent(T3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Q4.setBackground(new java.awt.Color(172, 125, 136));
        Q4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q4MousePressed(evt);
            }
        });

        T4.setForeground(new java.awt.Color(100, 56, 67));
        T4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_day_view_24px.png"))); // NOI18N

        javax.swing.GroupLayout Q4Layout = new javax.swing.GroupLayout(Q4);
        Q4.setLayout(Q4Layout);
        Q4Layout.setHorizontalGroup(
            Q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Q4Layout.setVerticalGroup(
            Q4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Q5.setBackground(new java.awt.Color(172, 125, 136));
        Q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Q5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Q5MousePressed(evt);
            }
        });

        T5.setForeground(new java.awt.Color(100, 56, 67));
        T5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/icons8_video_conference_24px.png"))); // NOI18N

        javax.swing.GroupLayout Q5Layout = new javax.swing.GroupLayout(Q5);
        Q5.setLayout(Q5Layout);
        Q5Layout.setHorizontalGroup(
            Q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(T5)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        Q5Layout.setVerticalGroup(
            Q5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Q5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Q2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Q1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(Q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPanes.setBackground(new java.awt.Color(0, 0, 51));
        jDesktopPanes.setPreferredSize(new java.awt.Dimension(740, 410));

        javax.swing.GroupLayout jDesktopPanesLayout = new javax.swing.GroupLayout(jDesktopPanes);
        jDesktopPanes.setLayout(jDesktopPanesLayout);
        jDesktopPanesLayout.setHorizontalGroup(
            jDesktopPanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPanesLayout.setVerticalGroup(
            jDesktopPanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPanes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void T1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_T1MousePressed

    private void Q1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MousePressed
        // TODO add your handling code here:
        Q1.setBackground(ClickedColor);
        Q2.setBackground(DefaultColor);
        Q3.setBackground(DefaultColor);
        Q4.setBackground(DefaultColor);
        Q5.setBackground(DefaultColor);
        
        MenuNames.setText("Add Job Opportunity");
    }//GEN-LAST:event_Q1MousePressed

    private void Q2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2MousePressed
        // TODO add your handling code here:
        Q1.setBackground(DefaultColor);
        Q2.setBackground(ClickedColor);
        Q3.setBackground(DefaultColor);
        Q4.setBackground(DefaultColor);
        Q5.setBackground(DefaultColor);
        
         MenuNames.setText("View Job Opportunities");
    }//GEN-LAST:event_Q2MousePressed

    private void Q3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3MousePressed
        // TODO add your handling code here:
        Q1.setBackground(DefaultColor);
        Q2.setBackground(DefaultColor);
        Q3.setBackground(ClickedColor);
        Q4.setBackground(DefaultColor);
        Q5.setBackground(DefaultColor);
        
         MenuNames.setText("Record Job Application");
    }//GEN-LAST:event_Q3MousePressed

    private void Q4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4MousePressed
        // TODO add your handling code here:
        Q1.setBackground(DefaultColor);
        Q2.setBackground(DefaultColor);
        Q3.setBackground(DefaultColor);
        Q4.setBackground(ClickedColor);
        Q5.setBackground(DefaultColor);
        
         MenuNames.setText("View Job Application");
    }//GEN-LAST:event_Q4MousePressed

    private void Q5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q5MousePressed
        // TODO add your handling code here:
        Q1.setBackground(DefaultColor);
        Q2.setBackground(DefaultColor);
        Q3.setBackground(DefaultColor);
        Q4.setBackground(DefaultColor);
        Q5.setBackground(ClickedColor);
        
         MenuNames.setText("Manage Interviews");
    }//GEN-LAST:event_Q5MousePressed

    private void Q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q2MouseClicked
        // TODO add your handling code here:
        ViewJob ViewJob = new ViewJob();
        jDesktopPanes.removeAll();
        jDesktopPanes.add(ViewJob).setVisible(true);
    }//GEN-LAST:event_Q2MouseClicked

    private void Q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q1MouseClicked
        // TODO add your handling code here:
        AddJob AddJob = new AddJob();
        jDesktopPanes.removeAll();
        jDesktopPanes.add(AddJob).setVisible(true);
        
    }//GEN-LAST:event_Q1MouseClicked

    private void T1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_T1MouseClicked

    private void Q3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q3MouseClicked
        // TODO add your handling code here:
        RecordJob RecordJob = new RecordJob();
        jDesktopPanes.removeAll();
        jDesktopPanes.add(RecordJob).setVisible(true);
    }//GEN-LAST:event_Q3MouseClicked

    private void Q4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q4MouseClicked
        // TODO add your handling code here:
        ViewJobAp ViewJobAp = new ViewJobAp();
        jDesktopPanes.removeAll();
        jDesktopPanes.add(ViewJobAp).setVisible(true);
    }//GEN-LAST:event_Q4MouseClicked

    private void Q5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Q5MouseClicked
        // TODO add your handling code here:
        
        ManageInter ManageInter = new ManageInter();
        jDesktopPanes.removeAll();
        jDesktopPanes.add(ManageInter).setVisible(true);
    }//GEN-LAST:event_Q5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuNames;
    private javax.swing.JPanel Q1;
    private javax.swing.JPanel Q2;
    private javax.swing.JPanel Q3;
    private javax.swing.JPanel Q4;
    private javax.swing.JPanel Q5;
    private javax.swing.JLabel T1;
    private javax.swing.JLabel T2;
    private javax.swing.JLabel T3;
    private javax.swing.JLabel T4;
    private javax.swing.JLabel T5;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
